[package]
name = "ktensor"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
num-traits = "0.2"
rand = "0.8.5"

[dev-dependencies]
plotters = "0.3.3"
